version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: |
          ls -l
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: |
          ls -l
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
